---
title: "CV"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A more complete CV can be found <a href="files/cv_rhodes.pdf" target="_blank">here</a>.

<br></br>

## Education and Training

+ Postdoctoral Research Fellow: *Rotman Research Institute* (2019 -- 2021)
+ Postdoctoral Research Fellow: *The University of Missouri* (2016 -- 2019)
+ PhD Psychology: *The University of Edinburgh* (2012 -- 2016)
+ MSc Human Cognitive Neuropsychology: *The University of Edinburgh* (2011 -- 2012)
+ BSc (hons) Psychology: *The University of Leeds* (2008 -- 2011)

<br></br>

## Publications

<!--
<a href="" target="_blank">[link]</a> 
<a href="" target="_blank" style="color:teal">(pdf)</a> 
<a href="" target="_blank" style="color:firebrick">(data/code)</a>
-->

- Rhodes, S., Doherty, J. M., Jaroslawska, A., Forsberg, A., Belletier, C., Naveh-Benjamin, M., Cowan, N., Barrouillet, P., Camos, V., & Logie, R. H. (*in press*). Exploring the influence of temporal factors on age differences in working memory dual task costs. *Psychology & Aging*. <a href="https://psyarxiv.com/esfm6/" target="_blank" style="color:teal">(pdf)</a> <a href="https://osf.io/p93af" target="_blank" style="color:firebrick">(data/code)</a>

- Jaroslawska, A. J., Rhodes, S.,  Belletier, C., Doherty, J. M., Cowan, N., Naveh-Benjamin, M., Barrouillet, P. Camos, V., & Logie, R. H. (*in press*). What Affects the Magnitude of Age-Related Dual-Task Costs in Working Memory? The Role of Stimulus Domain and Access to Semantic Representations. *The Quarterly Journal of Experimental Psychology*. <a href="https://journals.sagepub.com/doi/abs/10.1177/1747021820970744" target="_blank" style="color:teal">(pdf)</a> <a href="https://osf.io/srm36/" target="_blank" style="color:firebrick">(data/code)</a>

- Haaf, J. M., Rhodes, S., Naveh-Benjamin, M., Sun, T., Snyder, H. K., & Rouder, J. N. (2021). Revisiting the remember-know task: A replication of Gardiner and Java (1990). *Memory & Cognition, 49*, 46-66. <a href="https://link.springer.com/article/10.3758/s13421-020-01073-x" target="_blank">[link]</a> <a href="https://psyarxiv.com/2dyn7/" target="_blank" style="color:teal">(pdf)</a> <a href="https://osf.io/873sg" target="_blank" style="color:firebrick">(data/code)</a>

- Rhodes, S., Abbene, E., Meierhofer, A. M., & Naveh-Benjamin, M. (2020). Age differences in the precision of memory at short and long delays. *Psychology & Aging, 35*(8), 1073–1089. <a href="https://psycnet.apa.org/doiLanding?doi=10.1037%2Fpag0000565" target="_blank">[link]</a> <a href="https://psyarxiv.com/zucr3/" target="_blank" style="color:teal">(pdf)</a> <a href="https://github.com/stephenrho/delay-precision" target="_blank" style="color:firebrick">(data/code)</a>

- Cowan, N., Belletier, C., Doherty, J. M., Jaroslawska, A. J., Rhodes, S., Forsberg, A., Naveh-Benjamin, M., Barrouillet, P. Camos, V., & Logie, R. H. (2020). How do scientific views change? Notes from an extended adversarial collaboration. *Perspectives on Psychological Science, 15*(4), 1011-1025. <a href="https://journals.sagepub.com/doi/abs/10.1177/1745691620906415" target="_blank">[link]</a> <a href="http://stephenrho.github.io/files/cowan-et-al-2020.pdf" target="_blank" style="color:teal">(pdf)</a> 

- Morey, C., Rhodes, S. & Cowan, N. (2020). Co-existing, contradictory working memory models are ready for progressive refinement: Reply to Logie. *Cortex, 123*, 200-202. <a href="https://www.sciencedirect.com/science/article/pii/S0010945219303946" target="_blank">[link]</a> <a href="files/morey-rhodes-cowan-2019-reply.pdf" target="_blank" style="color:teal">(pdf)</a>

- Rhodes, S., Greene, N. R., & Naveh-Benjamin, M. (2019). Age-related differences in recall and recognition: A meta analysis. *Psychonomic Bulletin & Review, 26*(5), 1529-1547. <a href="https://link.springer.com/article/10.3758/s13423-019-01649-y" target="_blank">[link]</a> <a href="https://psyarxiv.com/6pvjd/" target="_blank" style="color:teal">(pdf)</a> <a href="https://osf.io/5gx86/" target="_blank" style="color:firebrick">(data/code)</a>

- Jaroslawska, A. J., & Rhodes, S. (2019). Adult age differences in the effects of processing on storage in working memory: A meta analysis. *Psychology & Aging, 34*(4), 512-530. <a href="https://psycnet.apa.org/record/2019-24512-001" target="_blank">[link]</a> <a href="files/Jaroslawska-Rhodes-PAG.pdf" target="_blank" style="color:teal">(pdf)</a> <a href="https://osf.io/bp359/" target="_blank" style="color:firebrick">(data/code)</a>

- Rhodes, S. & Cowan, N. (2019). Flexible representations in visual working memory and interactions with long-term learning: Commentary on the Special Issue. *British Journal of Psychology, 110*(2), 449-460. <a href="https://onlinelibrary.wiley.com/doi/abs/10.1111/bjop.12380" target="_blank">[link]</a> <a href="files/rhodes-cowan-bjp.pdf" target="_blank" style="color:teal">(pdf)</a>

- Rhodes, S., Jaroslawska, A. J., Doherty, J. M., Barrouillet, P., Camos, V., Cowan, N., Naveh-Benjamin, M., & Logie, R. H. (2019). Storage and processing in working memory: Assessing dual task performance and task prioritization across the adult lifespan. *Journal of Experimental Psychology: General, 148*(7), 1204-1227. <a href="https://www.ncbi.nlm.nih.gov/pubmed/30667263" target="_blank">[link]</a> <a href="https://www.researchgate.net/publication/328388904_Storage_and_processing_in_working_memory_Assessing_dual_task_performance_and_task_prioritization_across_the_adult_lifespan" target="_blank" style="color:teal">(pdf)</a> <a href="https://osf.io/b2epe/" target="_blank" style="color:firebrick">(data/code)</a>

- Doherty, J. M., Belletier, C., Rhodes, S., Jaroslawska, A., Camos, V., Barrouillet, P., Cowan, N., Naveh- Benjamin, M., & Logie, R. H. (2019). Dual-task costs in working memory: An adversarial collaboration. *Journal of Experimental Psychology: Learning, Memory, & Cognition, 45*(9), 1529-1551. <a href="https://www.ncbi.nlm.nih.gov/pubmed/30407025" target="_blank">[link]</a> <a href="https://www.researchgate.net/publication/327867355_Dual-task_costs_in_working_memory_An_adversarial_collaboration" target="_blank" style="color:teal">(pdf)</a> <a href="https://bit.ly/2KTKMgb" target="_blank" style="color:firebrick">(data/code)</a>

- Morey, C., Rhodes, S. & Cowan, N. (2019). Sensory-motor integration and brain lesions: Progress toward explaining domain-specific phenomena within domain-general working memory. *Cortex, 112*, 149-161. <a href="https://www.sciencedirect.com/science/article/pii/S0010945218304118" target="_blank">[link]</a> <a href="files/morey-rhodes-cowan-2018-cortex.pdf" target="_blank" style="color:teal">(pdf)</a> <a href="https://osf.io/wbmk7/" target="_blank" style="color:firebrick">(data/code)</a>

- Rhodes, S., Cowan, N., Parra, M. A., & Logie, R. H. (2019). Interaction effects on common measures of sensitivity: Choice of measure, type I error and power. *Behavior Research Methods, 51*(5), 2209-2227. <a href="https://link.springer.com/article/10.3758%2Fs13428-018-1081-0" target="_blank">[link]</a> <a href="files/Rhodes-et-al-BRM.pdf" target="_blank" style="color:teal">(pdf)</a> <a href="https://github.com/stephenrho/MeasuresAndErrors" target="_blank" style="color:firebrick">(data/code)</a>

- Rhodes, S. & Cowan, N. (2018). Attention in working memory: Attention is needed but it yearns to be free. *Annals of the New York Academy of Sciences, 1424*(1), 52-63. <a href="https://nyaspubs.onlinelibrary.wiley.com/doi/10.1111/nyas.13652" target="_blank">[link]</a> <a href="files/rhodes_cowan_nyas.pdf" target="_blank" style="color:teal">(pdf)</a>

- Rhodes, S., Cowan, N., Hardman, K. O., & Logie, R. H. (2018). Informed guessing in change detection. *Journal of Experimental Psychology: Learning, Memory, & Cognition, 44*(7), 1023-1035. <a href="https://www.ncbi.nlm.nih.gov/pubmed/29265829" target="_blank">[link]</a> <a href="https://github.com/stephenrho/Guessing/blob/master/paper/Rhodes_et_al_Guessing.pdf" target="_blank" style="color:teal">(pdf)</a> <a href="https://github.com/stephenrho/Guessing" target="_blank" style="color:firebrick">(data/code)</a>

- Rhodes, S., Parra, M. A., Cowan, N., & Logie, R. H. (2017). Healthy aging and visual working memory: The role of mixing feature and conjunction changes. *Psychology & Aging, 32*(4), 354-366. <a href="http://psycnet.apa.org/journals/pag/32/4/354/" target="_blank">[link]</a> <a href="files/RhodesEtAl2017.pdf" target="_blank" style="color:teal">(pdf)</a> <a href="https://github.com/stephenrho/BindingData/tree/master/RhodesEtAl_PsychAging" target="_blank" style="color:firebrick">(data/code)</a>

- Smith, K., Ricaud, B., Shahid, N., Rhodes, S., Starr, J. M., Ibanez, A., Parra, M. A., Escudero, J., & Vandergheynst, P. (2017). Locating temporal functional dynamics of visual short-term memory binding using graph modular Dirichlet energy. *Scientific Reports, 7*, 42013. <a href="https://www.nature.com/articles/srep42013" target="_blank">[link]</a> <a href="files/SmithEtAl2017.pdf" target="_blank" style="color:teal">(pdf)</a>

- Brown, L. A., Niven, E. H., Logie, R. H., Rhodes, S., & Allen, R. J. (2017). Visual feature binding in younger and older adults: Encoding and suffix interference effects. *Memory, 25*(2), 261-275. <a href="http://www.tandfonline.com/doi/full/10.1080/09658211.2016.1156705" target="_blank">[link]</a> <a href="files/BrownEtAlMemory.pdf" target="_blank" style="color:teal">(pdf)</a> 

- Rhodes, S., Parra, M. A., & Logie, R. H. (2016). Ageing and feature binding in visual working memory: The role of presentation time. *The Quarterly Journal of Experimental Psychology, 69*(4), 654-668. 
<a href="http://www.tandfonline.com/doi/abs/10.1080/17470218.2015.1038571" target="_blank">[link]</a> <a href="files/RhodesParraLogie2016.pdf" target="_blank" style="color:teal">(pdf)</a> <a href="https://github.com/stephenrho/BindingData/tree/master/RhodesEtAl_QJEP" target="_blank" style="color:firebrick">(data/code)</a>

- Rhodes, S., & Parra, M. A. (2016). *Executive functioning*. Encyclopedia of Geropsychology, Springer. <a href="http://link.springer.com/referencework/10.1007%2F978-981-287-080-3" target="_blank">[link]</a> <a href="files/RhodesAndParra_ExecutiveFunctioning.pdf" target="_blank" style="color:teal">(pdf)</a>

<br></br>

## In Progress

- Rhodes, S., Cowan, N., Parra, M. A., & Logie, R. H. (*under review*). Binding in short-term visual memory: Reassessing whole display interference. <a href="https://psyarxiv.com/rng4a/" target="_blank" style="color:firebrick">(pre-print)</a>

- Greene, N. R. & Rhodes, S. (*under review*). A tutorial on cognitive modeling for cognitive aging research. <a href="https://psyarxiv.com/qsnea/" target="_blank" style="color:firebrick">(pre-print)</a>

- Rhodes, S., Buchsbaum, B. R., & Hasher, L. (*under review*). The influence of long-term memory on working memory: Age-differences in proactive facilitation and interference. <a href="https://psyarxiv.com/gyjtz/" target="_blank" style="color:firebrick">(pre-print)</a> 

<br></br>

<!--
## Selected Posters and Presentations

Rhodes, S., Parra, M. A., Cowan, N., & Logie, R. H. (2016, May). *Healthy Ageing and Binding in Visual Working Memory: Mixed Versus Blocked Designs.* Poster presented at the International meeting of the Psychonomic Society, Granada, Spain. <a href="files/RhodesEtAlGranada.pdf" target="_blank" style="color:teal">(pdf)</a>

Rhodes, S., Parra, M. A., Cowan, N., & Logie, R. H. (2015, Nov). *Visual Working Memory and Change Detection: Reassessing Whole Display Interference.* Poster presented at the annual meeting of the Psychonomic Society, Chicago, Illinois. <a href="files/RhodesEtAlChicago.pdf" target="_blank" style="color:teal">(pdf)</a>

Rhodes, S., Parra, M. A., Cowan, N., & Logie, R. H. (2014, Nov). *The Effect of Age on Visual Working Memory for Features and Conjunctions.* Poster presented at the annual meeting of the Psychonomic Society, Long Beach, California. <a href="files/RhodesEtAlLongBeach.pdf" target="_blank" style="color:teal">(pdf)</a>

Rhodes, S., Parra, M. A., Cowan, N., & Logie, R. H. (2014, Sep). *Does Healthy Ageing Affect the Ability to Bind Features in Visual Working Memory?* Presented at the Seventh European Working Memory Symposium, Edinburgh.

Rhodes, S., Parra, M. A., Cowan, N., & Logie, R. H. (2014, Apr). *Is Feature Binding in Visual Working Memory Age Invariant?* Poster presented at the Cognitive Aging Conference 2014, Atlanta, Georgia. <a href="files/RhodesEtAlAtlanta.pdf" target="_blank" style="color:teal">(pdf)</a>
-->